create table genes (id bigint primary key generated by default as identity, gene text not null, gene_synonym text,
    ensembl text, gene_description text);

create table diseases (id bigint primary key generated by default as identity, name text not null);
create table genes_diseases (gene_id bigint not null references genes(id),
    disease_id bigint not null references diseases(id));

create table biological_processes (id bigint primary key generated by default as identity, name text not null);
create table genes_biological_processes (gene_id bigint references genes(id),
    biological_process_id bigint references biological_processes(id))
